Multiple Instances:

name: Doer-Gen

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  test:
   name: doer

   runs-on: windows-latest
   strategy:
    fail-fast: false
    matrix:
     runner: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
   steps:
     - run: |
          echo Hellow world
          echo this is second
